FROM nginx:alpine

# Copie des fichiers statiques
COPY frontend/ /usr/share/nginx/html/

# Configuration Nginx
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]